ruli: Delete -ansi and -pedantic from compiler commandline
The build fails because ruli is compiled with -ansi
(which implies C89/C90), but glibc's memchr macro
uses _Generic, a C11 feature. Clang treats this as
an error via -Werror,-Wc11-extensions.

Fixes build with glibc 2.43+

| ruli_conf.c:86:12: error: '_Generic' is a C11 extension [-Werror,-Wc11-extensions]
|    86 |       if (!memchr(inbuf, '\0', LOAD_SEARCH_LIST_INBUFSZ))
|       |            ^

Signed-off-by: Khem Raj <khem.raj@oss.qualcomm.com>