minizip: backport fix for the missing header
Minizip release v1.3.2 is missing required ints.h header that
causes build failure on components using it:

| ../../../../../recipe-sysroot/usr/include/minizip/ioapi.h:74:10: fatal error: ints.h: No such file or directory
|    74 | #include "ints.h"
|       |          ^~~~~~~~

Backport fix from https://github.com/madler/zlib/commit/cb14dc9ade3759352417a300e6c2ed73268f1d97

Signed-off-by: Samuli Piippo <samuli.piippo@qt.io>
Signed-off-by: Khem Raj <khem.raj@oss.qualcomm.com>